### ISSUE TITLE
Regarding errors while trying to stop vgs satellite docker container

### ISSUE THREAD

**Issue by devansh-dalal** [verygoodsecurity/vgs-satellite#162]
## Problem statement
Weird looking exception when trying to stop satellite docker in e2e tests.

```
vgs-satellite_1          | [INFO][2021-02-11 14:08:53,972][ProxyProcess-regular][MainThread] Stopping proxy.
vgs-satellite_1          | [INFO][2021-02-11 14:08:53,972][ProxyProcess-regular][MainThread] Stopped proxy.
vgs-satellite_1          | [INFO][2021-02-11 14:08:53,972][ProxyProcess-regular][MainThread] Stopping proxy.
vgs-satellite_1          | [INFO][2021-02-11 14:08:53,972][ProxyProcess-regular][MainThread] Stopped proxy.
vgs-satellite_1          | [INFO][2021-02-11 14:08:53,972][ProxyProcess-regular][MainThread] Stopping proxy.
vgs-satellite_1          | [INFO][2021-02-11 14:08:53,972][ProxyProcess-regular][MainThread] Stopped proxy.
vgs-satellite_1          | [INFO][2021-02-11 14:08:53,972][ProxyProcess-regular][MainThread] Stopping proxy.
vgs-satellite_1          | [INFO][2021-02-11 14:08:53,972][ProxyProcess-regular][MainThread] Stopping proxy.
vgs-satellite_1          | [INFO][2021-02-11 14:08:53,972][ProxyProcess-regular][MainThread] Stopped proxy.
vgs-satellite_1          | [INFO][2021-02-11 14:08:53,972][ProxyProcess-regular][MainThread] Stopped proxy.
vgs-satellite_1          | [INFO][2021-02-11 14:08:53,974][ProxyProcess-reverse][MainThread] Stopping proxy.
vgs-satellite_1          | [INFO][2021-02-11 14:08:53,976][ProxyProcess-reverse][MainThread] Stopped proxy.
vgs-satellite_1          | [INFO][2021-02-11 14:08:53,974][ProxyProcess-reverse][MainThread] Stopping proxy.
vgs-satellite_1          | [INFO][2021-02-11 14:08:53,976][ProxyProcess-reverse][MainThread] Stopped proxy.
vgs-satellite_1          | [INFO][2021-02-11 14:08:53,974][ProxyProcess-reverse][MainThread] Stopping proxy.
vgs-satellite_1          | [INFO][2021-02-11 14:08:53,976][ProxyProcess-reverse][MainThread] Stopped proxy.
vgs-satellite_1          | [INFO][2021-02-11 14:08:53,974][ProxyProcess-reverse][MainThread] Stopping proxy.
vgs-satellite_1          | [INFO][2021-02-11 14:08:53,976][ProxyProcess-reverse][MainThread] Stopped proxy.
vgs-satellite_1          | [INFO][2021-02-11 14:08:53,974][ProxyProcess-reverse][MainThread] Stopping proxy.
vgs-satellite_1          | [INFO][2021-02-11 14:08:53,976][ProxyProcess-reverse][MainThread] Stopped proxy.
vgs-satellite_1          | Traceback (most recent call last):
vgs-satellite_1          |   File "/usr/local/lib/python3.8/multiprocessing/queues.py", line 239, in _feed
vgs-satellite_1          |     obj = _ForkingPickler.dumps(obj)
vgs-satellite_1          |   File "/usr/local/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
vgs-satellite_1          |     cls(buf, protocol).dump(obj)
vgs-satellite_1          | TypeError: cannot pickle 'sqlite3.Connection' object
vgs-satellite_1          | Traceback (most recent call last):
vgs-satellite_1          |   File "/usr/local/lib/python3.8/multiprocessing/queues.py", line 239, in _feed
vgs-satellite_1          |     obj = _ForkingPickler.dumps(obj)
vgs-satellite_1          |   File "/usr/local/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
vgs-satellite_1          |     cls(buf, protocol).dump(obj)
vgs-satellite_1          | TypeError: cannot pickle 'sqlite3.Connection' object
vgs-satellite_1          | Traceback (most recent call last):
vgs-satellite_1          | Traceback (most recent call last):
vgs-satellite_1          |   File "/usr/local/lib/python3.8/multiprocessing/queues.py", line 239, in _feed
vgs-satellite_1          | Traceback (most recent call last):
vgs-satellite_1          |     obj = _ForkingPickler.dumps(obj)
vgs-satellite_1          |   File "/usr/local/lib/python3.8/multiprocessing/queues.py", line 239, in _feed
vgs-satellite_1          |   File "/usr/local/lib/python3.8/multiprocessing/queues.py", line 239, in _feed
vgs-satellite_1          |     obj = _ForkingPickler.dumps(obj)
vgs-satellite_1          |   File "/usr/local/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
vgs-satellite_1          |     cls(buf, protocol).dump(obj)
vgs-satellite_1          | TypeError: cannot pickle 'sqlite3.Connection' object
vgs-satellite_1          |     obj = _ForkingPickler.dumps(obj)
vgs-satellite_1          | Traceback (most recent call last):
vgs-satellite_1          |   File "/usr/local/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
vgs-satellite_1          |   File "/usr/local/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
vgs-satellite_1          |     cls(buf, protocol).dump(obj)
vgs-satellite_1          | TypeError: cannot pickle 'sqlite3.Connection' object
vgs-satellite_1          | Traceback (most recent call last):
vgs-satellite_1          |     cls(buf, protocol).dump(obj)
vgs-satellite_1          | TypeError: cannot pickle 'sqlite3.Connection' object
vgs-satellite_1          | Traceback (most recent call last):
vgs-satellite_1          |   File "/usr/local/lib/python3.8/multiprocessing/queues.py", line 239, in _feed
vgs-satellite_1          | Traceback (most recent call last):
vgs-satellite_1          |   File "/usr/local/lib/python3.8/multiprocessing/queues.py", line 239, in _feed
vgs-satellite_1          |   File "/usr/local/lib/python3.8/multiprocessing/queues.py", line 239, in _feed
vgs-satellite_1          |     obj = _ForkingPickler.dumps(obj)
vgs-satellite_1          |   File "/usr/local/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
vgs-satellite_1          |   File "/usr/local/lib/python3.8/multiprocessing/queues.py", line 239, in _feed
vgs-satellite_1          |     cls(buf, protocol).dump(obj)
vgs-satellite_1          |     obj = _ForkingPickler.dumps(obj)
vgs-satellite_1          |     obj = _ForkingPickler.dumps(obj)
vgs-satellite_1          |   File "/usr/local/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
vgs-satellite_1          |   File "/usr/local/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
vgs-satellite_1          |     cls(buf, protocol).dump(obj)
vgs-satellite_1          |     cls(buf, protocol).dump(obj)
vgs-satellite_1          | TypeError: cannot pickle 'sqlite3.Connection' object
vgs-satellite_1          | TypeError: cannot pickle 'sqlite3.Connection' object
vgs-satellite_1          |     obj = _ForkingPickler.dumps(obj)
vgs-satellite_1          |   File "/usr/local/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
vgs-satellite_1          |     cls(buf, protocol).dump(obj)
vgs-satellite_1          | TypeError: cannot pickle 'sqlite3.Connection' object
vgs-satellite_1          | TypeError: cannot pickle 'sqlite3.Connection' object
vgs-satellite_1          | Traceback (most recent call last):
vgs-satellite_1          |   File "/usr/local/lib/python3.8/multiprocessing/queues.py", line 239, in _feed
vgs-satellite_1          |     obj = _ForkingPickler.dumps(obj)
vgs-satellite_1          |   File "/usr/local/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
vgs-satellite_1          |     cls(buf, protocol).dump(obj)
Stopping tmp_e2e_workdir_vgs-satellite_1         ... done
```

### The compose file
```
vgs-satellite:
    image: verygood/satellite
    ports:
      - 9002:9002 # wiremock-rh-utas
      - 9003:9003 # wiremock-sabre-rest
      - 9004:9004 # wiremock-sabre-soap
      - 9005:9005 # wiremock-rh-amenities
      - 9006:9006 # echo server port
      - 9007:9007 # satellite management port
      - 9009:9009 # reverse proxy port
      - 9010:9010 # forward proxy port
    environment:
      SATELLITE_ROUTES_PATH: /data/combined_route.yaml
      SATELLITE_API_PORT: 9007
      SATELLITE_REVERSE_PROXY_PORT: 9009
      SATELLITE_FORWARD_PROXY_PORT: 9010
    volumes:
      - ./src/test/resources/vgs-routes:/data
```

**Comment by rozenbom** [comment]
Hi @devansh-dalal. Do these errors break your workflow somehow? We aware of such issues and eventually will fix them.
BTW I see there are lots of ports defined for the Satellite container but you need only 3.

**Comment by devansh-dalal** [comment]
does not break, but clean stop is not done sometimes. So, it can be fine for now.
I am aware of the only 3 ports needed, We are using `network_mode: satellite`, so that proxy works properly with local urls. They are not relavant to the discussion.
