### ISSUE TITLE
Does the Electron app not work on M1 macs?

### ISSUE THREAD

**Issue by blizkreeg** [verygoodsecurity/vgs-satellite#198]
## Problem statement
I'm unable to get the Electron app working on my m1 mac

## Scenario(s) to reproduce
When I setup the inbound route, any API call to it results in a connection reset. Even after I quit the app, the ports are in use and restarting the app I get this error:

```
Process ProxyProcess-regular:
Traceback (most recent call last):
File "mitmproxy/proxy/server.py", line 46, in __init__
File "mitmproxy/net/tcp.py", line 593, in __init__
OSError: [Errno 48] Address already in use

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "multiprocessing/process.py", line 315, in _bootstrap
File "satellite/proxy/process.py", line 78, in run
File "satellite/proxy/master.py", line 69, in __init__
File "mitmproxy/proxy/server.py", line 54, in __init__
mitmproxy.exceptions.ServerException: Error starting proxy server: OSError(48, 'Address already in use')
Traceback (most recent call last):
File "app.py", line 161, in <module>
File "click/core.py", line 829, in __call__
File "click/core.py", line 782, in main
File "click/core.py", line 1066, in invoke
File "click/core.py", line 610, in invoke
File "app.py", line 153, in main
File "satellite/web_application.py", line 119, in start
File "satellite/proxy/manager.py", line 66, in start
File "satellite/proxy/process.py", line 107, in wait_proxy_started
satellite.proxy.exceptions.ProxyError: Unable to start regular proxy.
[8452] Failed to execute script app

```

## Satellite config
```
~ $ cat ~/.vgs-satellite/config.yml
log_path: /tmp/satellite.log
```

## Satellite version
(what version of satellite are you running, for electron app - see `VGS Satellite > About`)

## Log
```
~ $ cat /tmp/satellite.log
[INFO][2021-06-03 15:26:28,481][MainProcess][MainThread] Deleted 0 expired aliases.
[INFO][2021-06-03 15:26:28,541][MainProcess][MainThread] Started proxy(regular) at 9099 port.
[INFO][2021-06-03 15:26:28,562][MainProcess][MainThread] Started proxy(reverse) at 9098 port.
[INFO][2021-06-03 15:26:28,565][MainProcess][MainThread] Web server listening at 8089 port.
[INFO][2021-06-03 15:26:28,722][MainProcess][MainThread] 204 HEAD / (127.0.0.1) 1.29ms
[INFO][2021-06-03 15:26:45,797][MainProcess][MainThread] 200 GET /route (::1) 9.38ms
[INFO][2021-06-03 15:27:45,249][MainProcess][MainThread] 200 OPTIONS /route/ec3f68a2-2353-4e2c-b3af-61e0d48bc158 (::1) 0.37ms
[INFO][2021-06-03 15:27:45,264][MainProcess][MainThread] 200 PUT /route/ec3f68a2-2353-4e2c-b3af-61e0d48bc158 (::1) 9.11ms
[INFO][2021-06-03 15:27:45,274][MainProcess][MainThread] 200 GET /route (::1) 2.35ms
[INFO][2021-06-03 15:27:49,557][MainProcess][MainThread] 304 GET /route (::1) 2.38ms
[INFO][2021-06-03 15:31:04,277][MainProcess][MainThread] Deleted 0 expired aliases.
[INFO][2021-06-03 15:32:55,553][MainProcess][MainThread] Deleted 0 expired aliases.
```

## Satellite origin
  - [x ] Desktop app (electron)
  - [ ] Docker image
  - [ ] Dev

**Comment by katkovalchuk** [comment]
Hello!

To help you here I need to check out your code and how you send requests. Please send me this info to support@verygoodsecurity.com and I'll help you get this resolved!
