### ISSUE TITLE
Method not allowed

### ISSUE THREAD

**Issue by joe-gordian-software** [verygoodsecurity/vgs-satellite#29]
I followed the steps in README.md. After running `npm start` the browser opens on :8081 and I get the following error:
```
Traceback (most recent call last):
  File "/home/joe/Dropbox/programming/vgs-satellite/venv/lib/python3.6/site-packages/tornado/web.py", line 1701, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/home/joe/Dropbox/programming/vgs-satellite/venv/lib/python3.6/site-packages/tornado/web.py", line 264, in _unimplemented_method
    raise HTTPError(405)
tornado.web.HTTPError: HTTP 405: Method Not Allowed
```

**Comment by aslepakurov** [comment]
Thanks, @joe-gordian-software for submitting this issue. The fact that browser opened on port 8081 means, that there is no `~/.mitmproxy/config.yaml` file. 
You need to define said file with following content:

```
listen_port: 9099
web_port: 8089
web_host: localhost
web_open_browser: false
```

Your browser should open 1234 port for UI.
